name: motiv_app
description: "Motivasyon takip uygulamasÄ±"
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.6
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  sqflite: ^2.3.3
  path: ^1.8.3
  url_launcher: ^6.2.4
  google_sign_in: ^6.2.1
  app_links: ^6.3.2
  purchases_flutter: ^8.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#1E2A3A"
  adaptive_icon_foreground: "assets/images/MotivAppIcon.png"
  image_path: "assets/images/MotivAppIcon.png"
